// Autogenerated from Pigeon (v14.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by IKeys.
NSObject<FlutterMessageCodec> *IKeysGetCodec(void);

@protocol IKeys
- (nullable NSString *)getApiKeyWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpIKeys(id<FlutterBinaryMessenger> binaryMessenger, NSObject<IKeys> *_Nullable api);

NS_ASSUME_NONNULL_END
